name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install
        run: pnpm install

      - name: Run core Build
        run: pnpm run build

      - name: Run Build
        run: pnpm run test:build

      - name: echo cname
        run: echo 'keyboard.elonehoo.xyz' > test/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: test/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
